Get a list of all stations:

In [3]:
import json
import requests

url_stations = 'http://barcelonaapi.marcpous.com/bicing/stations.json'
res_stations = requests.get(url_stations)
stations = json.loads(res_stations.text)

SyntaxError: invalid syntax (<ipython-input-3-f9e408e8e962>, line 7)

Arrange the data to be in lists:

In [2]:
station_id = []
station_name = []
station_lat = []
station_lon = []

for idx,i in enumerate(stations['data']['bici']):
    station_id.append(int(stations['data']['bici'][idx]['id']))
    station_name.append(stations['data']['bici'][idx]['name'])
    station_lat.append(float(stations['data']['bici'][idx]['lat']))
    station_lon.append(float(stations['data']['bici'][idx]['lon']))

Find out how many bikes are available at each of the selected stations:

In [3]:
import datetime

bikes = []
slots = []
dates = []
bikes_ok = []
slots_ok = []

for i in station_id:
    url_availability = 'http://wservice.viabicing.cat/v2/stations/'+str(i)
    res_availability = requests.get(url_availability)
    json_availability = json.loads(res_availability.text)
    
    try:
        bikes_num = json_availability['stations'][0]['bikes']
        slots_num = json_availability['stations'][0]['slots']
        dates.append(datetime.datetime.fromtimestamp(json_availability['updateTime']).strftime('%Y-%m-%d %H:%M:%S'))
    except:
        bikes_num = 0
        slots_num = 0
        
        try: 
            dates.append(dates[len(dates)-1])
        except:
            dates.append(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
            
    bikes.append(bikes_num)
    slots.append(slots_num)
    
    if int(bikes_num) >= 2:
        bikes_ok.append(True)
    else:
        bikes_ok.append(False)
        
    if int(slots_num) >= 2:
        slots_ok.append(True)
    else:
        slots_ok.append(False)

Create a dataframe so that we can easily filter out the non-available stations:

In [4]:
import pandas as pd
dataset = pd.DataFrame({'station_id':station_id,
                        'station_name':station_name,
                        'station_lat':station_lat,
                        'station_lon':station_lon,
                        'bikes':bikes,
                        'slots':slots,
                        'bikes_ok':bikes_ok,
                        'slots_ok':slots_ok,
                        'entry_date':dates
                       })
dataset

,bikes,bikes_ok,entry_date,slots,slots_ok,station_id,station_lat,station_lon,station_name
0,6,True,2018-07-11 22:17:07,19,True,1,41.397952,2.180042,"Gran Via Corts Catalanes, 760"
1,0,False,2018-07-11 22:17:07,0,False,10,41.385531,2.183527,"Pl. Comercial, 11"
2,1,False,2018-07-11 22:17:07,16,True,100,41.379135,2.144090,"Tarragona, 159"
3,7,True,2018-07-11 22:17:07,17,True,101,41.392988,2.143562,"Av. Pau Casals, 1"
4,0,False,2018-07-11 22:17:07,24,True,102,41.393093,2.143365,"Av. Pau Casals, 3"
5,15,True,2018-07-11 22:17:07,5,True,103,41.409856,2.188217,"Aragó, 629"
6,1,False,2018-07-11 22:17:07,25,True,104,41.410821,2.187365,"C/València, 621"
7,2,True,2018-07-11 22:17:07,16,True,105,41.389069,2.173424,"PL. Urquinaona, 9"
8,1,False,2018-07-11 22:17:07,19,True,106,41.405587,2.162317,"Pl. Joanic, 59"
9,0,False,2018-07-11 22:17:07,20,True,107,41.398298,2.153128,"Travessera de Gracia, 92"
10,5,True,2018-07-11 22:17:07,16,True,108,41.402314,2.164961,"Indústria, 10"
11,0,False,2018-07-11 22:17:07,21,True,109,41.390981,2.147370,"C/ Londres, 53"
12,0,False,2018-07-11 22:17:07,17,True,11,41.381689,2.193914,"Trelawny, 2"
13,6,True,2018-07-11 22:17:07,11,True,110,41.385554,2.154813,"Avda. Roma, 117"
14,10,True,2018-07-11 22:17:07,3,True,111,41.381096,2.153087,"Calabria, 135"
15,7,True,2018-07-11 22:17:07,13,True,112,41.377644,2.157250,"Floridablanca, 49"
16,25,True,2018-07-11 22:17:07,0,False,113,41.378836,2.160801,"Comte Borrell, 60"
17,18,True,2018-07-11 22:17:07,1,False,114,41.376801,2.173039,"Pl. Jean Genet, 1"
18,18,True,2018-07-11 22:17:07,1,False,115,41.383275,2.183704,"Marquès d'Argentera, 1"
19,3,True,2018-07-11 22:17:07,24,True,116,41.383718,2.191414,"Salvat Papasseit, 72"
20,15,True,2018-07-11 22:17:07,6,True,117,41.390666,2.197024,"Rosa Sensat, 9"
21,25,True,2018-07-11 22:17:07,0,False,118,41.391884,2.187302,"Pujades, 1"
22,13,True,2018-07-11 22:17:07,5,True,119,41.396632,2.182802,"Ausiàs March, 122"
23,1,False,2018-07-11 22:17:07,24,True,12,41.384538,2.195679,"pg marítim barceloneta, 23"
24,10,True,2018-07-11 22:17:07,7,True,120,41.404666,2.176515,"Lepant, 278"
25,12,True,2018-07-11 22:17:07,7,True,121,41.406293,2.178689,"Castillejos, 258"
26,1,False,2018-07-11 22:17:07,18,True,122,41.405435,2.166240,"Nàpols, 344"
27,0,False,2018-07-11 22:17:07,15,True,123,41.397411,2.167798,"Girona, 126"
28,1,False,2018-07-11 22:17:07,24,True,124,41.377131,2.190857,"Atlantida, 82"
29,0,False,2018-07-11 22:17:07,20,True,125,41.384426,2.195595,"Passeig Maritim, 31"
...,...,...,...,...,...,...,...,...,...
389,15,True,2018-07-11 22:18:08,3,True,71,41.381931,2.162969,"Floridablanca , 145"
390,2,True,2018-07-11 22:18:08,21,True,72,41.393173,2.157081,"Rosselló, 217"
391,1,False,2018-07-11 22:18:08,16,True,73,41.392846,2.155788,"Enric Granados, 99"
392,7,True,2018-07-11 22:18:08,13,True,74,41.389391,2.143102,"Josep Tarradellas, 129"
393,4,True,2018-07-11 22:18:08,17,True,75,41.385081,2.142868,"Josep Tarradellas, 58"
394,18,True,2018-07-11 22:18:08,13,True,76,41.391751,2.153123,"CORSEGA, 216"
395,0,False,2018-07-11 22:18:08,25,True,78,41.385598,2.163380,Pl. Universitat
396,2,True,2018-07-11 22:18:08,21,True,79,41.385736,2.163577,Pl. Universitat
397,6,True,2018-07-11 22:18:08,20,True,8,41.389088,2.183568,"Passeig lluís companys, 2"
398,2,True,2018-07-11 22:18:08,16,True,80,41.389687,2.159999,"Enric Granados, 35"
399,18,True,2018-07-11 22:18:08,0,False,81,41.378915,2.149174,"Vilamarí davant, 61"
400,6,True,2018-07-11 22:18:08,27,True,82,41.379016,2.153799,"Rocafort, 72"
401,17,True,2018-07-11 22:18:08,9,True,83,41.384075,2.153654,"Compte Borrell, 177"
402,18,True,2018-07-11 22:18:08,1,False,84,41.383374,2.157577,"Diputació, 152"
403,18,True,2018-07-11 22:18:08,6,True,85,41.375076,2.159046,"Paral·lel, 146"
404,24,True,2018-07-11 22:18:08,0,False,86,41.375064,2.163640,"Paral·lel, 114"
405,0,False,2018-07-11 22:18:08,21,True,87,41.383156,2.148506,"Mallorca, 41"
406,2,True,2018-07-11 22:18:08,19,True,88,41.393547,2.150764,"Londres, 101"
407,3,True,2018-07-11 22:18:08,20,True,89,41.387953,2.150169,"Rosselló, 101"
408,19,True,2018-07-11 22:18:08,7,True,9,41.385031,2.185249,"Marquès de l'Argentera, 17"
409,7,True,2018-07-11 22:18:08,11,True,90,41.388340,2.150825,"Rosselló, 108"
410,19,True,2018-07-11 22:18:08,11,True,91,41.380452,2.158403,"Comte Borrell, 119"
411,0,False,2018-07-11 22:18:08,16,True,92,41.393860,2.160237,"Provença, 241"
412,14,True,2018-07-11 22:18:08,6,True,93,41.375454,2.149786,"Gran Via, 375"
413,21,True,2018-07-11 22:18:08,1,False,94,41.375619,2.149889,"Gran Via, 375"
414,16,True,2018-07-11 22:18:08,13,True,95,41.376428,2.147734,"Tarragona, 103"
415,2,True,2018-07-11 22:18:08,19,True,96,41.374152,2.148154,"Gran Via, 361"
416,2,True,2018-07-11 22:19:08,18,True,97,41.378124,2.145389,"Tarragona, 141"
417,0,False,2018-07-11 22:19:08,18,True,98,41.380658,2.141697,"Viriat, 45"
418,0,False,2018-07-11 22:19:08,16,True,99,41.380632,2.141548,"Viriat, 53"

Import the *new* dataset into a SQL table:

In [5]:
import sqlite3
conn = sqlite3.connect("bicidb.db")
cursos = conn.cursor()

In [7]:
dataset.to_sql('historical_availability', con=conn, if_exists='append')

Load back the *full* dataset into a data frame:

In [8]:
pd.read_sql("SELECT * FROM historical_availability;", con=conn)

,index,bikes,bikes_ok,entry_date,slots,slots_ok,station_id,station_lat,station_lon,station_name
0,0,23,1,2018-07-04 12:50:07,1,0,1,41.397952,2.180042,"Gran Via Corts Catalanes, 760"
1,1,0,0,2018-07-04 12:50:07,0,0,10,41.385531,2.183527,"Pl. Comercial, 11"
2,2,15,1,2018-07-04 12:50:07,6,1,100,41.379135,2.144090,"Tarragona, 159"
3,3,18,1,2018-07-04 12:50:07,7,1,101,41.392988,2.143562,"Av. Pau Casals, 1"
4,4,10,1,2018-07-04 12:50:07,10,1,102,41.393093,2.143365,"Av. Pau Casals, 3"
5,5,2,1,2018-07-04 12:50:07,16,1,103,41.409856,2.188217,"Aragó, 629"
6,6,1,0,2018-07-04 12:50:07,23,1,104,41.410821,2.187365,"C/València, 621"
7,7,15,1,2018-07-04 12:50:07,2,1,105,41.389069,2.173424,"PL. Urquinaona, 9"
8,8,7,1,2018-07-04 12:50:07,12,1,106,41.405587,2.162317,"Pl. Joanic, 59"
9,9,1,0,2018-07-04 12:50:07,19,1,107,41.398298,2.153128,"Travessera de Gracia, 92"
10,10,2,1,2018-07-04 12:50:07,17,1,108,41.402314,2.164961,"Indústria, 10"
11,11,6,1,2018-07-04 12:50:07,15,1,109,41.390981,2.147370,"C/ Londres, 53"
12,12,0,0,2018-07-04 12:50:07,19,1,11,41.381689,2.193914,"Trelawny, 2"
13,13,5,1,2018-07-04 12:50:07,14,1,110,41.385554,2.154813,"Avda. Roma, 117"
14,14,1,0,2018-07-04 12:50:07,19,1,111,41.381096,2.153087,"Calabria, 135"
15,15,8,1,2018-07-04 12:50:07,12,1,112,41.377644,2.157250,"Floridablanca, 49"
16,16,4,1,2018-07-04 12:50:07,20,1,113,41.378836,2.160801,"Comte Borrell, 60"
17,17,11,1,2018-07-04 12:50:07,6,1,114,41.376801,2.173039,"Pl. Jean Genet, 1"
18,18,5,1,2018-07-04 12:50:07,13,1,115,41.383275,2.183704,"Marquès d'Argentera, 1"
19,19,10,1,2018-07-04 12:50:07,14,1,116,41.383718,2.191414,"Salvat Papasseit, 72"
20,20,13,1,2018-07-04 12:50:07,8,1,117,41.390666,2.197024,"Rosa Sensat, 9"
21,21,16,1,2018-07-04 12:50:07,8,1,118,41.391884,2.187302,"Pujades, 1"
22,22,4,1,2018-07-04 12:50:07,16,1,119,41.396632,2.182802,"Ausiàs March, 122"
23,23,7,1,2018-07-04 12:50:07,22,1,12,41.384538,2.195679,"pg marítim barceloneta, 23"
24,24,8,1,2018-07-04 12:50:07,11,1,120,41.404666,2.176515,"Lepant, 278"
25,25,5,1,2018-07-04 12:50:07,14,1,121,41.406293,2.178689,"Castillejos, 258"
26,26,1,0,2018-07-04 12:50:07,18,1,122,41.405435,2.166240,"Nàpols, 344"
27,27,0,0,2018-07-04 12:50:07,19,1,123,41.397411,2.167798,"Girona, 126"
28,28,20,1,2018-07-04 12:50:07,5,1,124,41.377131,2.190857,"Atlantida, 82"
29,29,0,0,2018-07-04 12:50:07,21,1,125,41.384426,2.195595,"Passeig Maritim, 31"
...,...,...,...,...,...,...,...,...,...,...
808,389,15,1,2018-07-11 22:18:08,3,1,71,41.381931,2.162969,"Floridablanca , 145"
809,390,2,1,2018-07-11 22:18:08,21,1,72,41.393173,2.157081,"Rosselló, 217"
810,391,1,0,2018-07-11 22:18:08,16,1,73,41.392846,2.155788,"Enric Granados, 99"
811,392,7,1,2018-07-11 22:18:08,13,1,74,41.389391,2.143102,"Josep Tarradellas, 129"
812,393,4,1,2018-07-11 22:18:08,17,1,75,41.385081,2.142868,"Josep Tarradellas, 58"
813,394,18,1,2018-07-11 22:18:08,13,1,76,41.391751,2.153123,"CORSEGA, 216"
814,395,0,0,2018-07-11 22:18:08,25,1,78,41.385598,2.163380,Pl. Universitat
815,396,2,1,2018-07-11 22:18:08,21,1,79,41.385736,2.163577,Pl. Universitat
816,397,6,1,2018-07-11 22:18:08,20,1,8,41.389088,2.183568,"Passeig lluís companys, 2"
817,398,2,1,2018-07-11 22:18:08,16,1,80,41.389687,2.159999,"Enric Granados, 35"
818,399,18,1,2018-07-11 22:18:08,0,0,81,41.378915,2.149174,"Vilamarí davant, 61"
819,400,6,1,2018-07-11 22:18:08,27,1,82,41.379016,2.153799,"Rocafort, 72"
820,401,17,1,2018-07-11 22:18:08,9,1,83,41.384075,2.153654,"Compte Borrell, 177"
821,402,18,1,2018-07-11 22:18:08,1,0,84,41.383374,2.157577,"Diputació, 152"
822,403,18,1,2018-07-11 22:18:08,6,1,85,41.375076,2.159046,"Paral·lel, 146"
823,404,24,1,2018-07-11 22:18:08,0,0,86,41.375064,2.163640,"Paral·lel, 114"
824,405,0,0,2018-07-11 22:18:08,21,1,87,41.383156,2.148506,"Mallorca, 41"
825,406,2,1,2018-07-11 22:18:08,19,1,88,41.393547,2.150764,"Londres, 101"
826,407,3,1,2018-07-11 22:18:08,20,1,89,41.387953,2.150169,"Rosselló, 101"
827,408,19,1,2018-07-11 22:18:08,7,1,9,41.385031,2.185249,"Marquès de l'Argentera, 17"
828,409,7,1,2018-07-11 22:18:08,11,1,90,41.388340,2.150825,"Rosselló, 108"
829,410,19,1,2018-07-11 22:18:08,11,1,91,41.380452,2.158403,"Comte Borrell, 119"
830,411,0,0,2018-07-11 22:18:08,16,1,92,41.393860,2.160237,"Provença, 241"
831,412,14,1,2018-07-11 22:18:08,6,1,93,41.375454,2.149786,"Gran Via, 375"
832,413,21,1,2018-07-11 22:18:08,1,0,94,41.375619,2.149889,"Gran Via, 375"
833,414,16,1,2018-07-11 22:18:08,13,1,95,41.376428,2.147734,"Tarragona, 103"
834,415,2,1,2018-07-11 22:18:08,19,1,96,41.374152,2.148154,"Gran Via, 361"
835,416,2,1,2018-07-11 22:19:08,18,1,97,41.378124,2.145389,"Tarragona, 141"
836,417,0,0,2018-07-11 22:19:08,18,1,98,41.380658,2.141697,"Viriat, 45"
837,418,0,0,2018-07-11 22:19:08,16,1,99,41.380632,2.141548,"Viriat, 53"